CONFIG_FOLDER: configs # Config files path
FOLDER: experiments # Experiment files saving path

TEST:
  FOLDER: results # Testing files saving path

DATASET:
  TASK_ROOT: deps/mGPT_instructions
  SMPL_PATH: deps/smpl
  TRANSFORM_PATH: deps/transforms/
  WORD_VERTILIZER_PATH: deps/glove/
  KIT:
    ROOT: datasets/kit-ml # KIT directory
    SPLIT_ROOT: datasets/kit-ml # KIT splits directory
    MEAN_STD_PATH: deps/t2m/
  HUMANML3D:
    ROOT: datasets/humanml3d # HumanML3D directory
    SPLIT_ROOT: datasets/humanml3d # HumanML3D splits directory
    MEAN_STD_PATH: deps/t2m/
